### PR TITLE
fix readme for Ultra96 and ZCU104 to get pynq-dpu notebooks

### PR DESCRIPTION
**Pull request by DavideConficconi**
Referencing to issue #87 to install pynq-dpu notebooks

### CODE REVIEW

**Comment by skalade** [comment]
Hi there,

Thank you for the PR. Referring back to your issue, what were your exact reproduction steps? Were you connecting to the board via a serial or ssh session? Most people won't need to source those scripts to install the notebooks if running from the jupyter lab terminal (which I admit should be more clear in the readme).

If you go through installation steps from the jupyter lab terminal you shouldn't see these issues. Only readme change I would make is "simply run:" -> "simply run in jupyter lab terminal:" and have a warning at the end in case you are in an ssh session instead with the steps that solved your issue.

Thanks
Shawn

**Comment by DavideConficconi** [comment]
Hi Shawn,

As you correctly guessed I was connecting to the board not through jupyter (both serial and ssh. 
I did not know that the process should happen through the jupyter lab terminal.

Currently, I even experienced some issues in the ZCU104 setup. 
I will try your procedure through jupyter notebooks terminal and get back to you.

In case everything works it might be a good solution your proposal of simply saying to run in jupyter lab terminal.
Anyhow, I believe that whatever installation procedure I should be able to login on the board via ssh/serial and test a command-line python script. Do you think this is valuable? In case maybe it is helpful to add a section in the README for the new PYNQ venv procedure. 

Thanks for the feedback

Davide

**Comment by DavideConficconi** [comment]
Hi @skalade,
I should have committed the updates to the readme as you suggested.
Let me know if there is anything you believe should be updated

Thanks
Davide

**Comment by skalade** [comment]
Thanks for the contribution!

**Pull request merged**
